name: Preview build

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v1.0.0
        with:
          node-version-file: .tool-versions
      - name: Build
        run: pnpm build
        shell: sh
      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1.5.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: 2023-hp
          directory: ./dist/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
