name: Release workflow

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3.5.3
      - id: release
        uses: google-github-actions/release-please-action@v3.7.10
        with:
          release-type: node
          include-v-in-tag: false
  deploy:
    needs: release-please
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v1.1.0
        with:
          node-version-file: .tool-versions
      - name: Build
        run: pnpm build
        shell: sh
      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1.5.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: 2023-hp
          directory: ./dist/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
